services:
  smart-brain-api:
    container_name: "Backend"
    build: ./ # This uses dockerfile
    working_dir: /usr/src/smart-brain-api
    command: npm start
    environment:
      POSTGRES_URI: postgres://mark:plier@postgres:5432/smart-brain
    links:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/smart-brain-api
    # copies data from current
    # directory to /usr/src/smart-brain-api
    # and also rebuilds on save in local file sys
    develop:
      watch:
        - action: rebuild
          path: .
          ignore: node_module/

  postgres:
    container_name: "Database"
    build: ./postgres
    volumes:
      - ./postgres/tables/:/docker-entrypoint-initdb.d/tables/
      # - ./postgres/deploy-schemas.sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: plier
      POSTGRES_DB: smart-brain
    ports:
      - "5432:5432"
