BEGIN TRANSACTION;

  CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email TEXT UNIQUE NOT NULl,
    entries BIGINT DEFAULT 0,
    joined TIMESTAMP NOT NULL
  );

COMMIT;
